# Generated by Django 4.2.10 on 2024-03-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nipracademy', '0006_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource',
            field=models.FileField(blank=True, upload_to='files/resource'),
        ),
    ]
