# Generated by Django 4.2.10 on 2024-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nipracademy', '0014_offlineadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineadmission',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
