# Generated by Django 4.2.10 on 2024-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nipracademy', '0021_rename_faculty_image_staffs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, upload_to='media/faculties_img', verbose_name='faculties')),
            ],
        ),
    ]
