# Generated by Django 4.2.10 on 2024-03-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nipracademy', '0022_faculties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
