# Generated by Django 4.2.10 on 2024-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nipracademy', '0024_alter_faculties_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/homepage_images')),
            ],
        ),
    ]
