# Generated by Django 4.2.10 on 2024-04-16 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nipracademy', '0025_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
